application: fantasy-frc
version: 1-5-0
runtime: python27
api_version: 1
module: default
threadsafe: false

handlers:
- url: /favicon\.ico
  static_files: static/icons/favicon.ico
  upload: static/icons/favicon\.ico
- url: /static
  static_dir: static
- url: /updateTeams/.*
  script: UpdateDB.application
  login: admin
- url: /leagueManagement/.*
  script: league_management.application
  login: required
- url: /allianceManagement/.*
  script: alliance_management.application
  login: required
- url: /draft/.*
  script: drafting.application
  login: required
- url: /thanks
  script: thanksPage.application
- url: /about
  script: aboutPage.application
- url: /help/.*
  script: helpPage.application
- url: /.*
  script: MainPage.application


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: pycrypto
  version: latest